plugins {
    id 'com.android.application'
}

android {
    namespace 'com.acho.chat.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.acho.chat.app"
        minSdk 25
        targetSdk 35
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    splits {
        abi {
            enable false
        }
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/**', '**.properties', '**.proto']
        }
    }
}

dependencies {
}
