name: Build Android APK + AAB

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 🔥 BUILD APK (release) con firma
      - name: Build Release APK
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > keystore.jks
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # 📦 BUILD AAB (release) con firma
      - name: Build Release AAB
        run: |
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # 📤 Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/release/*.apk

      # 📤 Upload AAB
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-aab
          path: app/build/outputs/bundle/release/*.aab
